builds:
  - id: routehead
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    binary: routehead

archives:
  - format: tar.gz
    name_template: >-
      routehead-
      {{- title .Os }}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  use: github
  sort: desc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: routehead
    name: client
  draft: true
  replace_existing_draft: true
  name_template: "Release {{.Tag}}"

